import { JewelleryItem, Testimonial, FAQItem } from './types';

export const CATEGORIES = [
  { id: 'rings', name: 'Rings', icon: '💍', count: 42 },
  { id: 'earrings', name: 'Earrings', icon: '✨', count: 32 },
  { id: 'necklaces', name: 'Necklaces', icon: '📿', count: 28 },
  { id: 'pendants', name: 'Pendants', icon: '💎', count: 18 },
  { id: 'mangalsutra', name: 'Mangalsutra', icon: '🖤', count: 12 },
  { id: 'bangles', name: 'Bangles', icon: '⭕', count: 24 },
  { id: 'bracelets', name: 'Bracelets', icon: '🔗', count: 15 },
  { id: 'gold-chains', name: 'Gold Chains', icon: '💫', count: 20 },
  { id: 'nose-pins', name: 'Nose Pins', icon: '🌟', count: 10 },
  { id: 'anklets', name: 'Anklets', icon: '👣', count: 8 },
  { id: 'kids', name: 'Kids Jewellery', icon: '🧸', count: 10 },
  { id: 'mens', name: 'Men\'s Jewellery', icon: '🤵', count: 14 },
  { id: 'coins', name: 'Gold Coins', icon: '🪙', count: 6 },
  { id: 'solitaires', name: 'Solitaires', icon: '☄️', count: 9 },
];

export const COLLECTIONS = [
  {
    id: 'bridal',
    name: 'Bridal Jewellery',
    tagline: 'Maang tikkas, heavy necklaces, and heritage ornaments for your special day.',
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1200&q=80',
  },
  {
    id: 'diamond',
    name: 'Diamond Collection',
    tagline: 'Scintillating diamonds crafted passionately in breathtaking platinum and gold silhouettes.',
    image: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=1200&q=80',
  },
  {
    id: 'gold',
    name: 'Gold Collection',
    tagline: 'Purest 22K BIS Hallmarked yellow gold legacy ornaments built with timeless traditional designs.',
    image: 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=1200&q=80',
  },
  {
    id: 'silver',
    name: 'Silver Jewellery Collection',
    tagline: 'Sterling 92.5 pure silver jewelry including designer chains, lightweight anklets, and gifts.',
    image: 'https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?auto=format&fit=crop&w=1200&q=80',
  },
  {
    id: 'mens-jewellery',
    name: 'Men\'s Collection',
    tagline: 'Refined gold chains, majestic bracelets, and heavy signature rings designed for the modern gentleman.',
    image: 'https://images.unsplash.com/photo-1618403088890-3d9ff6f4c8da?auto=format&fit=crop&w=1200&q=80',
  },
];

export const JEWELLERY_ITEMS: JewelleryItem[] = [
  // Rings
  {
    id: 'item-1',
    name: 'Aura Crown Solitaire Diamond Ring',
    category: 'Rings',
    collection: 'Diamond Collection',
    image: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=800&q=80',
    description: 'A brilliant-cut certified 1-carat solitaire diamond held gracefully by an 18K white gold crown setting, radiating exquisite sparkle and visual brilliance.',
    purity: '18K White Gold',
    sku: 'MJ-R-0128',
    tags: ['Solitaire', 'Rings', 'Engagement', 'Trending'],
    featured: true,
    trending: true,
  },
  {
    id: 'item-2',
    name: 'The Royal Sovereign Men\'s Gold Ring',
    category: 'Rings',
    collection: 'Men\'s Collection',
    image: 'https://images.unsplash.com/photo-1618403088890-3d9ff6f4c8da?auto=format&fit=crop&w=800&q=80',
    description: 'Elegant heavyweight 22K yellow gold signet ring styled with a bold crest and micro-engravings, reflecting royal command and modern masculine heritage.',
    purity: '22K Gold',
    sku: 'MJ-R-4920',
    tags: ['Rings', 'Gold', 'Mens', 'Heritage'],
    featured: true,
    trending: false,
  },
  {
    id: 'item-3',
    name: 'Princess Cut Dual Halo Diamond Ring',
    category: 'Rings',
    collection: 'Diamond Collection',
    image: 'https://images.unsplash.com/photo-1543294001-f7cbfe92237e?auto=format&fit=crop&w=800&q=80',
    description: 'A dual-layered diamond halo surrounding a perfect square princess-cut diamond core. Hand-crafted in durable, high-polish rose gold.',
    purity: '18K Rose Gold',
    sku: 'MJ-R-7210',
    tags: ['Rings', 'Diamond', 'Halo', 'Trending'],
    featured: false,
    trending: true,
  },

  // Necklaces
  {
    id: 'item-4',
    name: 'The Empress Emerald Bridal Choker Set',
    category: 'Necklaces',
    collection: 'Bridal Jewellery',
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=80',
    description: 'A breathtaking bridal necklace layered with high-grade Colombian emeralds and premium syndicate pear-cut diamonds. Complemented by matching hanging earrings.',
    purity: '18K Gold & Emerald',
    sku: 'MJ-N-9023',
    tags: ['Choker', 'Bridal', 'Emerald', 'Premium'],
    featured: true,
    trending: true,
  },
  {
    id: 'item-5',
    name: 'Mayur Heritage Temple Necklace',
    category: 'Necklaces',
    collection: 'Gold Collection',
    image: 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=800&q=80',
    description: 'A masterwork of antique South Indian Temple styling, showcasing peacock motifs hand-carved in 22K yellow gold with fine kundan studs.',
    purity: '22K Gold',
    sku: 'MJ-N-1284',
    tags: ['Necklaces', 'Temple', 'Gold', 'Peacock'],
    featured: true,
    trending: false,
  },

  // Earrings
  {
    id: 'item-6',
    name: 'Vedic Glow Gold Jhumkas',
    category: 'Earrings',
    collection: 'Gold Collection',
    image: 'https://images.unsplash.com/photo-1635767798638-3e25273a8236?auto=format&fit=crop&w=800&q=80',
    description: 'Flawlessly hand-carved chandelier pearls and kundan drops cascading from intricate filigree top domes in 100% BIS Hallmarked yellow gold.',
    purity: '22K Gold',
    sku: 'MJ-E-3392',
    tags: ['Earrings', 'Jhumka', 'Traditional', 'Gold'],
    featured: false,
    trending: true,
  },
  {
    id: 'item-7',
    name: 'Chandelier Cascade Diamond Drops',
    category: 'Earrings',
    collection: 'Diamond Collection',
    image: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=80',
    description: 'Elegant tiered diamond drops featuring delicate dangling pavé diamond leaves, catching light from every possible angle in platinum settings.',
    purity: 'Platinum 950',
    sku: 'MJ-E-0012',
    tags: ['Earrings', 'Diamond', 'Cascade', 'Trending'],
    featured: true,
    trending: true,
  },

  // Bangles and Bracelets
  {
    id: 'item-8',
    name: 'The Royal Kada Embossed Bangle',
    category: 'Bangles',
    collection: 'Gold Collection',
    image: 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=800&q=80',
    description: 'A traditional heavy kada bangle featuring beautifully intricate patterns of flora and fauna, finished in gold clasp-locks with safety chains.',
    purity: '22K Gold',
    sku: 'MJ-B-8422',
    tags: ['Bangles', 'Kada', 'Traditional'],
    featured: false,
    trending: false,
  },
  {
    id: 'item-9',
    name: 'Prism Flex Sterling Silver Bracelet',
    category: 'Bracelets',
    collection: 'Silver Jewellery Collection',
    image: 'https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?auto=format&fit=crop&w=800&q=80',
    description: 'A sterling 92.5 designer bracelet featuring geometric silver tiles and premium rhodium finish to withstand daily-wear oxidation.',
    purity: '92.5 Sterling Silver',
    sku: 'MJ-BR-1102',
    tags: ['Bracelets', 'Silver', 'DailyWear', 'Trending'],
    featured: false,
    trending: true,
  },

  // Others
  {
    id: 'item-10',
    name: 'Devi Shringar Gold Mangalsutra',
    category: 'Mangalsutra',
    collection: 'Gold Collection',
    image: 'https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?auto=format&fit=crop&w=800&q=80',
    description: 'Classic auspicious gold-and-black onyx bead chains holding an elegant dual-cup central flower pendant studded with selected VVS diamonds.',
    purity: '22K Gold / VVS Diamond',
    sku: 'MJ-M-5521',
    tags: ['Mangalsutra', 'Gold', 'Diamond', 'Traditional'],
    featured: true,
    trending: false,
  },
  {
    id: 'item-11',
    name: 'Saraswati Laxmi Gold Coin - 10G',
    category: 'Gold Coins',
    collection: 'Gold Collection',
    image: 'https://images.unsplash.com/photo-1589758438368-0ad531db3366?auto=format&fit=crop&w=800&q=80',
    description: '99.9% 24K pure gold coin minted beautifully with details of Goddess Laxmi and Goddess Saraswati, signifying absolute luxury storage and secure investment assets.',
    purity: '24K Pure Gold',
    sku: 'MJ-C-0010',
    tags: ['Investment', 'Coins', 'Festival'],
    featured: false,
    trending: false,
  },
  {
    id: 'item-12',
    name: 'Celestial Dew Nose Pin',
    category: 'Nose Pins',
    collection: 'Diamond Collection',
    image: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=800&q=80',
    description: 'A subtle starburst shaped diamond screw nose stud modeled in solid 18K yellow gold, adding high-society sparkle to traditional outfits.',
    purity: '18K Gold',
    sku: 'MJ-P-4428',
    tags: ['Nose Pins', 'Diamond', 'Minimalist'],
    featured: false,
    trending: false,
  }
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 't-1',
    name: 'Aishwarya Sharma',
    rating: 5,
    comment: 'The team at Mahavir Jewellers guided me smoothly during my bridal shopping. The customization process of my neck set was an incredible experience. Craftsmanship is unmatched!',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80',
    date: '3 weeks ago',
    verified: true,
  },
  {
    id: 't-2',
    name: 'Rajesh Kethan',
    rating: 5,
    comment: 'I bought my investment gold coins and custom wedding rings here. Trustworthy certification (BIS Hallmark and IGI), transparent billing, and a luxurious showroom feel.',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    date: '1 month ago',
    verified: true,
  },
  {
    id: 't-3',
    name: 'Meenakshi Jain',
    rating: 5,
    comment: 'Mahavir Jewellers holds generations of trust. My families have been purchasing from them since 1998. Their daily wear light weight gold necklaces and rings are absolutely beautiful.',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80',
    date: '2 months ago',
    verified: true,
  }
];

export const FAQS: FAQItem[] = [
  {
    id: 'faq-1',
    question: 'How do I check the purity of gold purchased at Mahavir Jewellers?',
    answer: 'Every piece of gold jewellery sold at Mahavir Jewellers is 100% certified with the BIS (Bureau of Indian Standards) Hallmark. You can verify the HUID code printed laser-sharp on the ornaments with the BIS CARE mobile application to guarantee pure 22K or 18K metal weight.',
  },
  {
    id: 'faq-2',
    question: 'Do you offer a diamond authenticity certificate?',
    answer: 'Yes. All our diamonds are internationally verified and certified by GIA, IGI, or SGL, assuring color, clarity, carat weight, and premium cut precision. We hand you physical certificates and online tracking URLs with every diamond product purchase.',
  },
  {
    id: 'faq-3',
    question: 'Is customized jewellery design available at your store?',
    answer: 'Absolutely! Our bespoke jewellery service lets you bring blueprints, sketches, or reference photos. Our personal jewel experts use state-of-the-art 3D CAD modeling to draft drafts, share exact estimates, and cast custom ornaments within 10 to 14 working days.',
  },
  {
    id: 'faq-4',
    question: 'What is your exchange and buyback policy?',
    answer: 'We provide 100% exchange and buyback value for our hallmark gold as per daily bullion rates. For diamond jewellery, buyback and exchange are provided at prevailing rates minus craft-making charges, backed by our lifetime warranty policy.',
  },
  {
    id: 'faq-5',
    question: 'How does the Video Consultation booking system work?',
    answer: 'Simply click "Book Appointment", choose your desired Date & Time, and select "Video Call". You will receive SMS & WhatsApp confirmations containing a Google Meet link. Our dedicated specialist jewellery consultant will answer calls live from the VIP consultation room.',
  }
];
